-- SELECT
--     f.id,
--     ff1.fighter,
--     ff2.fighter
-- FROM
--     fights f,
--     fight_fighters ff1,
--     fight_fighters ff2
-- WHERE
--     ff1.fight = f.id AND
--     ff2.fight = f.id AND
--     ff1.fighter != ff2.fighter AND
--     f.id = 1;